apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.23.7
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: gitea-data
              mountPath: /data
          env:
            - name: GITEA__server__DOMAIN
              value: gitea.nozomu.dev
            - name: GITEA__server__HTTP_PORT
              value: "3000"
            - name: GITEA__server__ROOT_URL
              value: https://gitea.nozomu.dev
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-pvc
