apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://github.com/argoproj/argo-cd/raw/refs/tags/v2.14.10/manifests/install.yaml
  - base/argocd-ingress.yaml

patches:
  # - path: overlays/production/argocd-cm-patch.yaml
  - path: overlays/production/argocd-cmd-params-cm-patch.yaml
  - path: overlays/production/argocd-server-service.yaml
